apiVersion: v1
kind: Service
metadata:
  name: apphub-website
  labels:
    app.kubernetes.io/name: apphub-website
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: apphub-marketing
spec:
  selector:
    app.kubernetes.io/name: apphub-website
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: apphub-marketing
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
